spring.application.name=LearningPlatformValidation

# Datasource Oracle
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:XE
spring.datasource.username=EFTS9
spring.datasource.password=EFTS9
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

#HikariCP configuration

spring.datasource.hikari.connection-test-query=SELECT 1 FROM DUAL
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.pool-name=HikariPool

#Hibernate configuration
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#Session config
spring.session.jdbc.initialize-schema=always
spring.sql.init.mode=always
spring.sql.init.platform=oracle


# Actuator endpoints configuration
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
